- name: Get vSphere login session
  ansible.builtin.uri:
    url: "https://{{ vcenter_hostname }}/rest/com/vmware/cis/session"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    force_basic_auth: true
    url_username: "{{ vcenter_username }}"
    url_password: "{{ vcenter_password }}"
  register: login_response

- name: Get list of datastores
  ansible.builtin.uri:
    url: "https://{{ vcenter_hostname }}/rest/vcenter/datastore"
    method: GET
    headers:
      Content-Type: "application/json"
      vmware-api-session-id: "{{ login_response.json.value }}"
  register: datastore_response

- name: datastores
  ansible.builtin.debug:
    var: datastore_response

- name: Filter datastores starting with prefix 'workload_share'
  set_fact:
    filtered_datastores: "{{ datastore_response.json.value | json_query(query) }}"
  vars:
    query: "[?starts_with(name, 'workload_share')].{name: name, free_space: summary.free_space}"

- name: Choose the least used datastore
  set_fact:
    vcenter_datastore: "{{ filtered_datastores | sort(attribute='free_space') | first}}"

- name: Deploy Virt Plan
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Plan
      metadata:
        name: "{{ plan_name }}"
        namespace: openshift-mtv
      spec:
        archived: false
        description: ''
        map:
          network:
            name: "test-network"
            namespace: openshift-mtv
          storage:
            name: "test-storage"
            namespace: openshift-mtv
        provider:
          destination:
            name: host
            namespace: openshift-mtv
          source:
            name: vmware
            namespace: openshift-mtv
        targetNamespace: openshift-mtv
        vms:
          - hooks: []
            id: vm-1508016
          - hooks: []
            id: vm-1508020
        warm: false
